services:
  redis:
    image: 'redis:7-alpine'
    ports:
      - 6379
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

  worker:
    image: int1
    build: .
    environment:
      REDIS_URL: redis://redis
    links:
      - redis
    entrypoint: bin/launch_sidekiq

  web:
    image: int1
    build: .
    environment:
      REDIS_URL: redis://redis
    links:
      - redis
    entrypoint: bin/launch_web -o 0.0.0.0
    ports:
      - 3000:3000

